load_and_install_if_necessary <- function(package_name) {
  if (!suppressPackageStartupMessages(library(package_name, character.only=TRUE, logical.return=TRUE))) {
    cat(paste0("Package ", package_name, " not found. Will install it."))
    install.packages(package_name)
    library(package_name, character.only=TRUE)
  }
}

load_data_file <- function (file, row_names, version = 0, sha = "") {
  if (missing(row_names)) {
    # these row names are hard coded and might not be applicable
    # names like this are generated by ReBench
    row_names <- c("Invocation", "Iteration", "Value", "Unit", "Criterion",
                   "Benchmark", "VM", "Suite", "Extra", "Cores", "InputSize",
                   "Var")
  }
  
  bench <- read.table(file, sep="\t", header=FALSE, col.names=row_names, fill=TRUE)
  
  # Give Run Ids to the rows, but need to consider different criterions
  num_criteria <- length(levels(bench$Criterion))
  if (num_criteria < 1) {
    num_criteria = 1
  }
  
  bench$Extra <- factor(bench$Extra)
  bench$Cores <- factor(bench$Cores)
  bench$Suite <- factor(bench$Suite)
  
  bench <- mutate(bench, version = version, sha = sha)
  bench
}

theme_simple <- function(font_size = 8) {
  theme_bw() +
    theme(axis.text.x          = element_text(size = font_size, lineheight=0.7, colour = "#000000"),
          axis.title.x         = element_blank(),
          axis.title.y         = element_text(size = font_size, colour = "#000000"),
          axis.text.y          = element_text(size = font_size, colour = "#000000"),
          axis.line            = element_line(colour = "gray"),
          plot.title           = element_text(size = font_size, colour = "#000000"),
          legend.text          = element_text(size = font_size, colour = "#000000"),
          legend.title         = element_blank(),
          legend.background    = element_blank(),
          panel.background     = element_blank(), #element_rect(fill = NA, colour = NA),
          panel.grid.major     = element_blank(),
          panel.grid.minor     = element_blank(),
          panel.border         = element_blank(),
          plot.background      = element_blank(), #element_rect(fill = NA, colour = NA)
          strip.background     = element_blank(),
          strip.text           = element_text(size = font_size, colour = "#000000"),
          plot.margin = unit(c(0,0,0,0), "cm"))
}


load_and_install_if_necessary("dplyr")
load_and_install_if_necessary("ggplot2")
load_and_install_if_necessary("ggstance")
load_and_install_if_necessary("tables")
load_and_install_if_necessary("psych")
